{
  "welcome": "🎓 <b>Ассалому алайкум!</b>\n\nМактаб Бошқарув Ботига хуш келибсиз.",
  "choose_language": "🌐 <b>Тилни танланг</b>",
  "lang_selected": "✅ Тил танланди: Ўзбекча",
  "share_phone_prompt": "📱 <b>Телефон рақамингизни юборинг</b>\n\nБу тугмани босинг — Telegram автоматик юборади 👇",
  "share_phone_button": "📱 Телефон рақамни юбориш",
  "phone_received": "✅ Раҳмат!\n\n📱 Рақам: <code>{phone}</code>\n\n🔍 Тизимдан қидирилмоқда...",
  "user_not_found": "❌ Кечирасиз, бу рақам тизимда топилмади.\n\nИлтимос, админ билан боғланинг.",
  "role_student": "🎓 Хуш келибсиз, ўқувчи!",
  "role_parent": "👨‍👩‍👧 Хуш келибсиз, ҳурматли ота-она!",
  "role_teacher": "👨‍🏫 Хуш келибсиз, ҳурматли ўқитувчи!",
  "role_admin": "👨‍💼 Хуш келибсиз, админ!",
  "welcome_user": "🎓 Хуш келибсиз, <b>{name}</b>!\n\nСинф: {class_name}",
  "menu_title": "🎓 <b>Асосий меню</b>\n\nҚуйидаги тугмалардан бирини танланг:",
  "btn_grades": "📊 Баҳоларим",
  "btn_schedule": "📅 Жадвалим",
  "btn_attendance": "📔 Давоматим",
  "btn_homework": "📚 Уй вазифам",
  "btn_rating": "🏆 Рейтингім",
  "btn_achievements": "🎯 Ютуқларим",
  "btn_ai": "🤖 AI Ёрдамчи",
  "btn_contact": "📞 Алоқа",
  "btn_settings": "⚙️ Созламалар",
  "btn_menu": "🏠 Асосий меню",
  "btn_child": "👦 Фарзандим",
  "btn_payments": "💰 Тўлов",
  "btn_classes": "🏫 Синфларим",
  "btn_mark_attendance": "✅ Давомат",
  "btn_mark_grade": "📝 Баҳолаш",
  "btn_stats": "📊 Статистика",
  "btn_announce": "📢 Эълон",
  "btn_students": "👥 Ўқувчилар",
  "btn_broadcast": "📤 Ботни таништириш",
  "btn_premium": "🎁 Премиум",
  "btn_report": "📈 Ҳисобот",
  "btn_sync": "🔄 Sync",
  "no_grades": "📭 Ҳозирча баҳолар йўқ.",
  "grades_title": "📊 <b>БАҲОЛАРИНГИЗ</b>",
  "avg_grade": "📈 Ўртача: <b>{avg}</b>",
  "total_grades": "📋 Жами: <b>{count}</b> та баҳо",
  "no_schedule": "📭 Жадвал юкланмаган.",
  "schedule_title": "📅 <b>ҲАФТАЛИК ЖАДВАЛ</b>",
  "no_attendance": "📭 Давомат маълумоти йўқ.",
  "attendance_title": "📔 <b>ДАВОМАТ</b>",
  "no_homework": "📭 Ҳозирча уй вазифаси йўқ.",
  "no_rating": "📭 Рейтинг маълумоти йўқ.",
  "rating_title": "🏆 <b>СИНФ РЕЙТИНГИ</b>",
  "your_place": "🥉 Сизнинг ўрнингиз: <b>{place}</b>",
  "ai_welcome": "🤖 <b>AI Ёрдамчи</b>\n\nСаволингизни ёзинг, мен жавоб бераман.",
  "ai_thinking": "🤔 Ўйлаяпман...",
  "ai_error": "❌ AI хато. Кейинроқ уриниб кўринг.",
  "ai_limit": "⚠️ Кунлик лимит тугади. Эртага қайта уриниб кўринг.",
  "settings_title": "⚙️ <b>Созламалар</b>",
  "change_language": "🌐 Тилни ўзгартириш",
  "notifications_on": "🔔 Билдиришномалар ёқилган",
  "notifications_off": "🔕 Билдиришномалар ўчирилган",
  "unknown_command": "🤔 Тушунмадим.\n\nИлтимос, менюдан фойдаланинг ёки /start босинг.",
  "error": "❌ Хатолик юз берди. Қайта уриниб кўринг.",
  "share_own_phone": "❌ Илтимос, ўз рақамингизни юборинг.",
  "btn_parent_grades": "📋 Фарзандим баҳолари",
  "btn_parent_attendance": "📔 Фарзандим давомати",
  "btn_parent_schedule": "📅 Фарзандим жадвали",
  "btn_parent_rating": "🏆 Фарзандим рейтинги",
  "btn_teacher_schedule": "📅 Синф жадвали",
  "btn_teacher_homework": "📚 Уй вазифалари",
  "btn_admin_students": "👥 Барча ўқувчилар",
  "btn_admin_classes": "🏫 Синф маълумоти",
  "btn_admin_staff": "👨‍🏫 Ходимлар рўйхати",
  "btn_admin_grades": "📊 Синф баҳолари",
  "btn_admin_schedule": "📅 Синф жадвали (админ)",
  "btn_admin_rating": "🏆 Синф рейтинги",
  "no_grade_today": "баҳо йўқ",
  "help_group": "ℹ️ <b>Гуруҳ буйруқлари</b>\n\n• /jadval — ҳафталик жадвал\n• /reyting — синф рейтинги\n• /menu — ботни шахсий чатда очиш"
}
